In [11]:
# 向量量化过程得梯度反传
import torch
import torch.nn.functional as F
import torch.nn as nn

In [65]:
x = torch.randn((4,3), requires_grad=True)
# print(x.sum()/2)

# # 使用索引划分聚类
# delta_onehot = torch.tensor(
#     [
#         [1, 1, 0, 0], 
#         [0, 0, 1, 1]
#     ],
#     dtype=torch.float32,
#     requires_grad=True
# )
# center = torch.einsum('cl,ld->cd', delta_onehot, x)
# center = center / delta_onehot.sum(dim=-1, keepdim=True)
# # center = center / delta_onehot.sum(dim=-1).unsqueeze(-1)
# # center = center / torch.tensor([2, 2]).unsqueeze(-1)
# loss = center.sum()
# # print(loss)
# center.retain_grad()
# loss.backward()
# print(center.grad)
# print(x.grad)

# delta_onehot_nograd = torch.tensor(
#     [
#         [1, 1, 0, 0], 
#         [0, 0, 1, 1]
#     ],
#     dtype=torch.float32,
#     requires_grad=False
# )
# center_nograd = torch.einsum('cl,ld->cd', delta_onehot_nograd, x)
# center_nograd = center_nograd / delta_onehot_nograd.sum(dim=-1, keepdim=True)
# loss_nograd = center_nograd.sum()
# # print(loss_nograd)
# loss_nograd.backward()
# print(x.grad)

# 使用池化聚类
# print(x)
y = x.permute(1, 0)
net = nn.AvgPool1d(2, 2)
center = net(y).permute(1, 0)
# print(center)
center.retain_grad()
loss = center.sum()
loss.backward()
print(center.grad)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])


In [85]:
a = torch.tensor([0.9, 0.9, 1, 1], dtype=torch.float32) * 10
print(a.softmax(dim=0))

tensor([0.1749, 0.1749, 0.4754, 0.1749])
